


spring.datasource.url=jdbc:mysql://database-1.chm84wmu46wh.ap-south-1.rds.amazonaws.com:3306/wallet_db
spring.datasource.username=admin
spring.datasource.password=WjtLS2W8LAWebSD 
spring.jpa.hibernate.ddl=update


