

spring.datasource.url=jdbc:mysql://database-1.chm84wmu46wh.ap-south-1.rds.amazonaws.com:3306/wallet_db
spring.datasource.username=admin
spring.datasource.password=WjtLS2W8LAWebSD

spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aasifmohd1385@gmail.com
spring.mail.password=oldjqlqxlukqlotl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true